Mender support
xaptum/buildroot pull request #1
Opened 2019-01-25 20:35 UTC by dberliner

2019-01-25 20:42 UTC, dberliner commented on package/go/go.mk
> +ifeq ($(BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS),y)
To be clear what we're doing, this will produce a compiler that can be run on the target if it is supported. A compiler that can run on the host is always built and that compiler can target all supported systems.

2019-01-29 17:17 UTC, drbild requested changes
A few comments, mostly related to getting this upstream.

2019-01-29 17:17 UTC, drbild commented on package/go/go.mk
> +ifeq ($(BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS),y)
So there are really three things:

1) Go compiler to run on the host (if so, can build host packages)
2) Go compiler to run on the host and support the target arch (if so, can build target packages)
3) Go compiler to run on the target.

However, I don't think Buildroot should support option 3.  They have an explicit policy of [not adding compilers to the target image](https://buildroot.org/downloads/manual/manual.html#faq-no-compiler-on-target).  So there's no reason to even build the Go compiler for the target arch.

So this can be simplified to just build the Go compiler for the host.  No `GOARCH`, etc.) when building the compiler.

The target support is then just (1) is the arch supported and (2) what `GOARCH`, etc. to set when compiling target packages.

2019-01-29 17:17 UTC, drbild commented on package/go/go.mk
> +ifeq ($(BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS),y)
So for submission upstream, I'd split this into four commits, starting from the current Buildroot master.

1) Do not build the go compiler for the target arch.
1) Rework the `*_SUPPORTS` flags as suggested in Thomas's email.
1) Add the `host-golang-package` command (basically Mirza's patch, but slightly modified).
1) Add the mender artifact package (basically Mirza's patch).

2019-01-29 17:17 UTC, drbild commented on package/go/Config.in.host
> +config BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS
Are there any existing Go packages that need to be updated to depend on this new variable, instead of the old `BR2_PACKAGE_HOST_GO_ARCH_SUPPORTS`?

2019-01-29 19:50 UTC, dberliner commented on package/go/Config.in.host
> +config BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS
Not within buildroot, it wouldn't surprise me if the HOST variable is being used as a proxy for target support in some packages but that's not ours to change. We should update the documentation, though.

2019-01-29 20:30 UTC, dberliner commented on package/go/Config.in.host
> +config BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS
Actually, looking at it further I think they all warrant changing. The condition is now much easier to pass (no longer asking if the target supports go) and could cause build commands to be issued for non-supported packages. There's only a few to update so it won't be difficult .

2019-01-29 20:39 UTC, dberliner commented on package/go/go.mk
> +ifeq ($(BR2_PACKAGE_HOST_GO_TARGET_ARCH_SUPPORTS),y)
I've removed the code accomplishing 3 and 2 has been accomplished by modifying packages that call target builds to use the new variable.

2019-01-29 21:00 UTC, drbild reviewed
I think this looks good functionally.

To get it accepted upstream, I think the commits will need to be reorganized so that
- each commit is one logical change
- no commit breaks anything.

Currently the commit to spit the `*_SUPPORTS` variables breaks building some packages. That isn't fixed until the last commit that updates those packages.

Also, the commits will need to have a detailed commit message explaining the change.

So I still think you'll want the following series:
1) do not build the Go toolchain to run on the target (one logical change, fixes what is essentially unwanted behavior in the current master)
1) separate Go host and target arch support (this commit will also update any packages that depend on target support)
1) add support to build Go packages for host
1) add mender-artifact package.

2019-02-01 13:27 UTC, mirzak commented
Overall looks great!

Couple of remarks,

- You will need to add Signed-off-by, tags for all commit. That is part of the commit message
- The current release of "mender-artifact" is 2.4.0, we might as well bump that as I noticed that the current package is 2.2.0.

2019-02-07 21:32 UTC, mirzak commented
It seems that someone else also revived my initial patch series, https://patchwork.ozlabs.org/cover/1037529/

2019-02-07 21:37 UTC, drbild commented
Nice!  We'll see if that gets accepted.

@dberliner After our current deadline, you could try Angelo Compagnucci's patches instead of ours. If they work, then send a reply with `Tested-by: Daniel Berliner <daniel.berliner@xaptum.com>` for each to the listserv.

2020-10-21 20:08 UTC, dberliner commented
I do not remember what happened her but this issue was solved a very long time ago.

2020-10-21 20:08 UTC, closed without merging